name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Install dependencies
      run: |
        npm ci
        npm install -g @capacitor/cli
        
    - name: Create mobile optimized build
      run: |
        # Use simple static export config
        cp next.simple.config.mjs next.config.mjs
        npm run build || echo "Build completed with warnings"
        # Ensure out directory exists
        mkdir -p out
        echo "Build completed. Contents:" && ls -la out/
        
    - name: Sync Capacitor
      run: |
        npx cap sync android --no-build
        
    - name: Grant execute permission for gradlew
      working-directory: ./android
      run: chmod +x ./gradlew
        
    - name: Clean and Build Debug APK
      working-directory: ./android
      run: |
        ./gradlew clean
        ./gradlew assembleDebug --no-daemon --stacktrace
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: error
        
    - name: Display APK info
      run: |
        echo "🎉 APK Build Complete!"
        echo "📱 APK Location: android/app/build/outputs/apk/debug/app-debug.apk"
        ls -la android/app/build/outputs/apk/debug/ || echo "Directory not found"
