name: Minimal APK Generator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Download and setup Android SDK
      run: |
        cd $HOME
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mkdir -p android-sdk/cmdline-tools
        mv cmdline-tools android-sdk/cmdline-tools/latest
        
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
        
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-28" "build-tools;28.0.3"
        
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
        
    - name: Create minimal Android project
      run: |
        mkdir -p connect-social-app/app/src/main/java/com/connectsocial/app
        mkdir -p connect-social-app/app/src/main/res/{values,layout}
        mkdir -p connect-social-app/gradle/wrapper
        
        cd connect-social-app
        
        # Create build.gradle (root)
        cat > build.gradle << 'EOF'
        buildscript {
            repositories {
                google()
                mavenCentral()
            }
            dependencies {
                classpath 'com.android.tools.build:gradle:7.0.4'
            }
        }
        
        allprojects {
            repositories {
                google()
                mavenCentral()
            }
        }
        EOF
        
        # Create settings.gradle
        cat > settings.gradle << 'EOF'
        include ':app'
        EOF
        
        # Create gradle.properties
        cat > gradle.properties << 'EOF'
        android.useAndroidX=true
        android.enableJetifier=true
        EOF
        
        # Create app/build.gradle
        cat > app/build.gradle << 'EOF'
        apply plugin: 'com.android.application'
        
        android {
            compileSdkVersion 28
            
            defaultConfig {
                applicationId "com.connectsocial.app"
                minSdkVersion 21
                targetSdkVersion 28
                versionCode 1
                versionName "1.0"
            }
            
            buildTypes {
                release {
                    minifyEnabled false
                }
            }
            
            compileOptions {
                sourceCompatibility JavaVersion.VERSION_1_8
                targetCompatibility JavaVersion.VERSION_1_8
            }
        }
        
        dependencies {
            implementation 'androidx.appcompat:appcompat:1.3.1'
        }
        EOF
        
        # Create AndroidManifest.xml
        cat > app/src/main/AndroidManifest.xml << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <manifest xmlns:android="http://schemas.android.com/apk/res/android"
            package="com.connectsocial.app">
            
            <application
                android:allowBackup="true"
                android:label="Connect Social"
                android:theme="@style/AppTheme">
                
                <activity
                    android:name=".MainActivity"
                    android:exported="true">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                </activity>
            </application>
        </manifest>
        EOF
        
        # Create MainActivity.java
        cat > app/src/main/java/com/connectsocial/app/MainActivity.java << 'EOF'
        package com.connectsocial.app;
        
        import android.os.Bundle;
        import android.webkit.WebView;
        import androidx.appcompat.app.AppCompatActivity;
        
        public class MainActivity extends AppCompatActivity {
            @Override
            protected void onCreate(Bundle savedInstanceState) {
                super.onCreate(savedInstanceState);
                
                WebView webView = new WebView(this);
                webView.getSettings().setJavaScriptEnabled(true);
                
                String html = "<html><body style='margin:0;padding:20px;font-family:Arial,sans-serif;background:linear-gradient(135deg,#667eea,#764ba2);color:white;text-align:center;height:100vh;display:flex;align-items:center;justify-content:center'>" +
                    "<div><h1 style='font-size:2em;margin-bottom:20px'>📱 Connect Social</h1>" +
                    "<p style='font-size:1.2em;margin-bottom:30px'>Welcome to your social media app!</p>" +
                    "<button onclick=\"alert('Hello from Connect Social!')\" style='background:rgba(255,255,255,0.2);border:2px solid white;color:white;padding:15px 30px;border-radius:25px;font-size:16px;cursor:pointer'>Get Started</button>" +
                    "</div></body></html>";
                    
                webView.loadData(html, "text/html", "UTF-8");
                setContentView(webView);
            }
        }
        EOF
        
        # Create strings.xml
        cat > app/src/main/res/values/strings.xml << 'EOF'
        <resources>
            <string name="app_name">Connect Social</string>
        </resources>
        EOF
        
        # Create styles.xml
        cat > app/src/main/res/values/styles.xml << 'EOF'
        <resources>
            <style name="AppTheme" parent="Theme.AppCompat.Light">
                <item name="colorPrimary">#667eea</item>
                <item name="colorPrimaryDark">#764ba2</item>
            </style>
        </resources>
        EOF
        
        # Create gradle wrapper
        cat > gradle/wrapper/gradle-wrapper.properties << 'EOF'
        distributionBase=GRADLE_USER_HOME
        distributionPath=wrapper/dists
        distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-all.zip
        zipStoreBase=GRADLE_USER_HOME
        zipStorePath=wrapper/dists
        EOF
        
        # Download gradlew
        curl -s https://raw.githubusercontent.com/gradle/gradle/v7.3.3/gradlew > gradlew
        chmod +x gradlew
        
    - name: Build APK
      run: |
        cd connect-social-app
        ./gradlew clean assembleDebug --stacktrace --info --no-daemon
        
        if [ -f "app/build/outputs/apk/debug/app-debug.apk" ]; then
          echo "✅ SUCCESS: APK built!"
          ls -la app/build/outputs/apk/debug/
        else
          echo "❌ FAILED: APK not found"
          find . -name "*.apk" || echo "No APK files found anywhere"
          exit 1
        fi
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: connect-social-minimal-apk
        path: connect-social-app/app/build/outputs/apk/debug/app-debug.apk
