name: Standalone APK Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Java 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Install Android SDK
      run: |
        cd $HOME
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mkdir -p android-sdk/cmdline-tools
        mv cmdline-tools android-sdk/cmdline-tools/latest
        
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
        
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools"
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-29" 
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;29.0.3"
        
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
        
    - name: Create Android project structure
      run: |
        # Create complete Android project structure manually
        mkdir -p android/app/src/main/{java/com/connectsocial/app,res/{values,layout,mipmap-hdpi,mipmap-mdpi,mipmap-xhdpi,mipmap-xxhdpi,mipmap-xxxhdpi,drawable},assets/public}
        
        # Create AndroidManifest.xml
        cat > android/app/src/main/AndroidManifest.xml << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <manifest xmlns:android="http://schemas.android.com/apk/res/android"
            package="com.connectsocial.app">
            
            <uses-permission android:name="android.permission.INTERNET" />
            <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
            
            <application
                android:allowBackup="true"
                android:icon="@mipmap/ic_launcher"
                android:label="Connect Social"
                android:theme="@style/AppTheme">
                
                <activity
                    android:name=".MainActivity"
                    android:exported="true"
                    android:launchMode="singleTask"
                    android:theme="@style/AppTheme.NoActionBarLaunch">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                </activity>
            </application>
        </manifest>
        EOF
        
        # Create MainActivity.java
        cat > android/app/src/main/java/com/connectsocial/app/MainActivity.java << 'EOF'
        package com.connectsocial.app;
        
        import android.os.Bundle;
        import android.webkit.WebView;
        import android.webkit.WebViewClient;
        import androidx.appcompat.app.AppCompatActivity;
        
        public class MainActivity extends AppCompatActivity {
            private WebView webView;
            
            @Override
            protected void onCreate(Bundle savedInstanceState) {
                super.onCreate(savedInstanceState);
                
                webView = new WebView(this);
                webView.getSettings().setJavaScriptEnabled(true);
                webView.getSettings().setDomStorageEnabled(true);
                webView.setWebViewClient(new WebViewClient());
                
                String html = "<!DOCTYPE html>" +
                    "<html><head>" +
                    "<meta charset='UTF-8'>" +
                    "<meta name='viewport' content='width=device-width, initial-scale=1.0'>" +
                    "<title>Connect Social</title>" +
                    "<style>" +
                    "body { margin: 0; padding: 20px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; min-height: 100vh; display: flex; align-items: center; justify-content: center; }" +
                    ".container { text-align: center; max-width: 400px; }" +
                    ".logo { font-size: 3em; margin-bottom: 20px; }" +
                    "h1 { margin: 20px 0; }" +
                    ".btn { background: rgba(255,255,255,0.2); border: 2px solid white; color: white; padding: 15px 30px; border-radius: 25px; font-size: 16px; margin: 10px; cursor: pointer; }" +
                    "</style></head><body>" +
                    "<div class='container'>" +
                    "<div class='logo'>📱</div>" +
                    "<h1>Connect Social</h1>" +
                    "<p>Your social media experience starts here!</p>" +
                    "<button class='btn' onclick=\"alert('Welcome to Connect Social! 🎉')\">Get Started</button>" +
                    "<button class='btn' onclick=\"alert('Connect Social - Built with ❤️')\">About</button>" +
                    "</div></body></html>";
                
                webView.loadData(html, "text/html", "UTF-8");
                setContentView(webView);
            }
        }
        EOF
        
        # Create strings.xml
        cat > android/app/src/main/res/values/strings.xml << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <resources>
            <string name="app_name">Connect Social</string>
        </resources>
        EOF
        
        # Create styles.xml
        cat > android/app/src/main/res/values/styles.xml << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <resources>
            <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
                <item name="colorPrimary">#667eea</item>
                <item name="colorPrimaryDark">#764ba2</item>
                <item name="colorAccent">#667eea</item>
            </style>
            <style name="AppTheme.NoActionBarLaunch" parent="AppTheme">
                <item name="android:windowNoTitle">true</item>
                <item name="android:windowActionBar">false</item>
                <item name="android:windowFullscreen">true</item>
            </style>
        </resources>
        EOF
        
        # Create simple launcher icon (placeholder)
        cat > android/app/src/main/res/drawable/ic_launcher_background.xml << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <vector android:height="108dp" android:width="108dp" android:viewportHeight="108" android:viewportWidth="108" xmlns:android="http://schemas.android.com/apk/res/android">
            <path android:fillColor="#667eea" android:pathData="M0,0h108v108h-108z"/>
        </vector>
        EOF
        
    - name: Create build files
      run: |
        # Create build.gradle (project level)
        cat > android/build.gradle << 'EOF'
        buildscript {
            repositories {
                google()
                mavenCentral()
            }
            dependencies {
                classpath 'com.android.tools.build:gradle:7.4.2'
            }
        }
        
        allprojects {
            repositories {
                google()
                mavenCentral()
            }
        }
        EOF
        
        # Create settings.gradle
        cat > android/settings.gradle << 'EOF'
        include ':app'
        EOF
        
        # Create app build.gradle
        cat > android/app/build.gradle << 'EOF'
        apply plugin: 'com.android.application'
        
        android {
            compileSdkVersion 29
            defaultConfig {
                applicationId "com.connectsocial.app"
                minSdkVersion 21
                targetSdkVersion 29
                versionCode 1
                versionName "1.0"
            }
            buildTypes {
                release {
                    minifyEnabled false
                }
            }
            compileOptions {
                sourceCompatibility JavaVersion.VERSION_1_8
                targetCompatibility JavaVersion.VERSION_1_8
            }
        }
        
        dependencies {
            implementation 'androidx.appcompat:appcompat:1.4.0'
        }
        EOF
        
        # Create gradle wrapper
        cat > android/gradle/wrapper/gradle-wrapper.properties << 'EOF'
        distributionBase=GRADLE_USER_HOME
        distributionPath=wrapper/dists
        distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.1-all.zip
        zipStoreBase=GRADLE_USER_HOME
        zipStorePath=wrapper/dists
        EOF
        
        # Create gradlew
        curl -s https://raw.githubusercontent.com/gradle/gradle/master/gradlew > android/gradlew
        chmod +x android/gradlew
        
    - name: Build APK
      run: |
        cd android
        ./gradlew assembleDebug --no-daemon
        
        if [ -f "app/build/outputs/apk/debug/app-debug.apk" ]; then
          echo "✅ APK built successfully!"
          ls -la app/build/outputs/apk/debug/
        else
          echo "❌ APK build failed"
          exit 1
        fi
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: connect-social-standalone-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
