name: Ultra Simple APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Install Android SDK manually
      run: |
        # Download and setup Android SDK
        cd $HOME
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mkdir -p android-sdk/cmdline-tools
        mv cmdline-tools android-sdk/cmdline-tools/latest
        
        # Set environment variables
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
        
        # Accept all licenses
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
        
        # Install required SDK components
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools"
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-29"
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;29.0.3"
        
        # Export for next steps
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        
    - name: Install Capacitor
      run: |
        npm install -g @capacitor/cli @capacitor/core @capacitor/android
        
    - name: Create simple app
      run: |
        # Create basic HTML app
        mkdir -p www
        cat > www/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Connect Social</title>
            <style>
                body { 
                    margin: 0; 
                    padding: 20px; 
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    color: white;
                    min-height: 100vh;
                    display: flex;
                    align-items: center;
                    justify-content: center;
                }
                .container { text-align: center; max-width: 400px; }
                .logo { font-size: 3em; margin-bottom: 20px; }
                h1 { margin: 20px 0; }
                .btn { 
                    background: rgba(255,255,255,0.2); 
                    border: 2px solid white; 
                    color: white; 
                    padding: 15px 30px; 
                    border-radius: 25px; 
                    font-size: 16px; 
                    margin: 10px;
                    cursor: pointer;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="logo">📱</div>
                <h1>Connect Social</h1>
                <p>Your social media experience starts here!</p>
                <button class="btn" onclick="showWelcome()">Get Started</button>
                <button class="btn" onclick="showInfo()">About</button>
            </div>
            
            <script>
                function showWelcome() {
                    alert('Welcome to Connect Social! 🎉');
                }
                function showInfo() {
                    alert('Connect Social - Built with ❤️ using Capacitor');
                }
            </script>
        </body>
        </html>
        EOF
        
    - name: Initialize Capacitor
      run: |
        npx cap init "Connect Social" "com.connectsocial.app" --web-dir=www
        npx cap add android
        
    - name: Build APK
      run: |
        cd android
        chmod +x ./gradlew
        ./gradlew assembleDebug --no-daemon
        
        # Verify APK exists
        if [ -f "app/build/outputs/apk/debug/app-debug.apk" ]; then
          echo "✅ APK built successfully!"
          ls -la app/build/outputs/apk/debug/
        else
          echo "❌ APK build failed"
          exit 1
        fi
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: connect-social-apk-final
        path: android/app/build/outputs/apk/debug/app-debug.apk
